# Generated by Django 5.1.3 on 2024-11-25 01:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seasons', '0002_season_created_by_season_updated_by'),
        ('teams', '0003_team_short_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_captain', models.BooleanField()),
                ('position', models.CharField(choices=[('defense', 'Defense'), ('forward', 'Forward'), ('goalie', 'Goalie')], max_length=16)),
                ('registered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('signature', models.CharField(max_length=512)),
                ('location', models.CharField(choices=[('brooklyn', 'Brooklyn'), ('bronx', 'Bronx'), ('manhattan', 'Manhattan'), ('queens', 'Queens'), ('long_island', 'Long Island'), ('new_jersey', 'New Jersey'), ('connecticut', 'Connecticut'), ('westchester', 'Westchester')], max_length=16)),
                ('interested_in', models.TextField(blank=True, null=True)),
                ('mid_season_party_ideas', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_team_registrations', to='seasons.season')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_season_registrations', to='teams.team')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='season_registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'season', 'team'), name='user_season_team_uniq')],
            },
        ),
    ]
