# Generated by Django 5.1.4 on 2024-12-27 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userseasonregistration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userseasonregistration',
            name='interested_in',
        ),
        migrations.AddField(
            model_name='userseasonregistration',
            name='interested_in_next_year',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userseasonregistration',
            name='interested_in_opening_closing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userseasonregistration',
            name='interested_in_other',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userseasonregistration',
            name='interested_in_reffing',
            field=models.BooleanField(default=False),
        ),
    ]
