# Generated by Django 5.1.4 on 2024-12-19 20:23

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_teamseasonregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamseasonregistration',
            name='away_games_played',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teamseasonregistration',
            name='home_games_played',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teamseasonregistration',
            name='games_played',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('home_games_played'), '+', models.F('away_games_played')), output_field=models.PositiveSmallIntegerField()),
        ),
    ]
