# Generated by Django 5.1.4 on 2024-12-20 20:56

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_teamseasonregistration_away_games_played_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamseasonregistration',
            name='away_overtime_losses',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teamseasonregistration',
            name='away_regulation_losses',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teamseasonregistration',
            name='away_shootout_losses',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teamseasonregistration',
            name='away_overtime_wins',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teamseasonregistration',
            name='away_regulation_wins',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teamseasonregistration',
            name='away_shootout_wins',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teamseasonregistration',
            name='away_ties',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teamseasonregistration',
            name='home_overtime_losses',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teamseasonregistration',
            name='home_regulation_losses',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teamseasonregistration',
            name='home_shootout_losses',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teamseasonregistration',
            name='home_overtime_wins',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teamseasonregistration',
            name='home_regulation_wins',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teamseasonregistration',
            name='home_shootout_wins',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teamseasonregistration',
            name='home_ties',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teamseasonregistration',
            name='away_losses',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('away_regulation_losses'), '+', models.F('away_overtime_losses')), '+', models.F('away_shootout_losses')), output_field=models.PositiveSmallIntegerField()),
        ),
        migrations.AddField(
            model_name='teamseasonregistration',
            name='away_wins',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('away_regulation_wins'), '+', models.F('away_overtime_wins')), '+', models.F('away_shootout_wins')), output_field=models.PositiveSmallIntegerField()),
        ),
        migrations.AddField(
            model_name='teamseasonregistration',
            name='overtime_losses',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('home_overtime_losses'), '+', models.F('away_overtime_losses')), output_field=models.PositiveSmallIntegerField()),
        ),
        migrations.AddField(
            model_name='teamseasonregistration',
            name='regulation_losses',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('home_regulation_losses'), '+', models.F('away_regulation_losses')), output_field=models.PositiveSmallIntegerField()),
        ),
        migrations.AddField(
            model_name='teamseasonregistration',
            name='home_losses',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('home_regulation_losses'), '+', models.F('home_overtime_losses')), '+', models.F('home_shootout_losses')), output_field=models.PositiveSmallIntegerField()),
        ),
        migrations.AddField(
            model_name='teamseasonregistration',
            name='losses',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('home_regulation_losses'), '+', models.F('home_overtime_losses')), '+', models.F('home_shootout_losses')), '+', models.F('away_regulation_losses')), '+', models.F('away_overtime_losses')), '+', models.F('away_shootout_losses')), output_field=models.PositiveSmallIntegerField()),
        ),
        migrations.AddField(
            model_name='teamseasonregistration',
            name='shootout_losses',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('home_shootout_losses'), '+', models.F('away_shootout_losses')), output_field=models.PositiveSmallIntegerField()),
        ),
        migrations.AddField(
            model_name='teamseasonregistration',
            name='overtime_wins',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('home_overtime_wins'), '+', models.F('away_overtime_wins')), output_field=models.PositiveSmallIntegerField()),
        ),
        migrations.AddField(
            model_name='teamseasonregistration',
            name='regulation_wins',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('home_regulation_wins'), '+', models.F('away_regulation_wins')), output_field=models.PositiveSmallIntegerField()),
        ),
        migrations.AddField(
            model_name='teamseasonregistration',
            name='home_wins',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('home_regulation_wins'), '+', models.F('home_overtime_wins')), '+', models.F('home_shootout_wins')), output_field=models.PositiveSmallIntegerField()),
        ),
        migrations.AddField(
            model_name='teamseasonregistration',
            name='shootout_wins',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('home_shootout_wins'), '+', models.F('away_shootout_wins')), output_field=models.PositiveSmallIntegerField()),
        ),
        migrations.AddField(
            model_name='teamseasonregistration',
            name='wins',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('home_regulation_wins'), '+', models.F('home_overtime_wins')), '+', models.F('home_shootout_wins')), '+', models.F('away_regulation_wins')), '+', models.F('away_overtime_wins')), '+', models.F('away_shootout_wins')), output_field=models.PositiveSmallIntegerField()),
        ),
        migrations.AddField(
            model_name='teamseasonregistration',
            name='ties',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('home_ties'), '+', models.F('away_ties')), output_field=models.PositiveSmallIntegerField()),
        ),
    ]
