# Generated by Django 5.1.4 on 2024-12-26 13:20

import django.db.models.expressions
import django.db.models.functions.comparison
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_teamseasonregistration_away_goals_against_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamseasonregistration',
            name='record',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.functions.text.Concat(django.db.models.functions.comparison.Cast(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('home_regulation_wins'), '+', models.F('home_overtime_wins')), '+', models.F('home_shootout_wins')), '+', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('away_regulation_wins'), '+', models.F('away_overtime_wins')), '+', models.F('away_shootout_wins'))), output_field=models.CharField()), models.Value('-'), django.db.models.functions.comparison.Cast(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('home_regulation_losses'), '+', models.F('home_overtime_losses')), '+', models.F('home_shootout_losses')), '+', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('away_regulation_losses'), '+', models.F('away_overtime_losses')), '+', models.F('away_shootout_losses'))), output_field=models.CharField()), models.Value('-'), django.db.models.functions.comparison.Cast(django.db.models.expressions.CombinedExpression(models.F('home_ties'), '+', models.F('away_ties')), output_field=models.CharField())), output_field=models.CharField()),
        ),
    ]
