# Generated by Django 5.1.4 on 2024-12-28 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0010_teamseasonregistration_point_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='short_name',
            field=models.CharField(help_text='Shorter version of name in all uppercase, ex: GREM.', max_length=10, unique=True),
        ),
    ]
