# Generated by Django 5.1.3 on 2024-11-11 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_created_by_game_updated_by_gameday_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='games', to='games.gameday'),
        ),
    ]
