# Generated by Django 5.1.3 on 2024-11-14 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_gamereferee'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='type',
            field=models.CharField(choices=[('regular', 'Regular'), ('playoff', 'Playoff')], default='regular', max_length=8),
        ),
    ]
