# Generated by Django 5.1.3 on 2024-11-21 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_gamegoal'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('regular', 'Regular'), ('playoff', 'Playoff')], default='scheduled', max_length=16),
        ),
    ]
