# Generated by Django 5.1.4 on 2024-12-19 01:20

import django.db.models.deletion
from django.db import migrations, models


def forwards_func(apps, schema_editor):
    GameGoal = apps.get_model('games', 'GameGoal')

    for goal in GameGoal.objects.select_related('game', 'game__home_team', 'game__away_team').iterator():
        game = goal.game
        home_team = game.home_team
        away_team = game.away_team

        goal.team_against = away_team if goal.team == home_team else home_team
        goal.save()


def reverse_func(apps, schema_editor):
    GameGoal = apps.get_model('games', 'GameGoal')

    for goal in GameGoal.objects.iterator():
        goal.team_against = None
        goal.save()


class Migration(migrations.Migration):
    dependencies = [
        ('games', '0008_game_status'),
        ('teams', '0004_teamseasonregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamegoal',
            name='team_against',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='goals_against', to='teams.team'),
        ),
        migrations.RunPython(forwards_func, reverse_func),
        migrations.AlterField(
            model_name='gamegoal',
            name='team_against',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goals_against',
                                    to='teams.team'),
        ),
        migrations.AlterField(
            model_name='gamegoal',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goals_for',
                                    to='teams.team'),
        ),
    ]
